---
downloads: ~/.ansible-downloads/

configure_sudoers: no
configure_terminal: no
configure_osx: no

dotfiles_repo: https://github.com/henning/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/Documents/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitconfig
  - .gitignore
  - .inputrc
  #- .osx
  - .vimrc

homebrew_installed_packages:
  - bash-completion
  - git
  - gpg
  - ssh-copy-id
  - openssl
  - wget
  - gradle
  - npm 
  - pyenv-virtualenvwrapper
  - bash
  - fish
  - macvim
  - aws-elasticbeanstalk
  - awscli
  - python3
  - mysql

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - homebrew/binary
  - homebrew/dupes
  - homebrew/versions

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - dropbox
  - firefox
  - google-chrome
  - sublime-text
  - vagrant
  - virtualbox
  - keepassx
  - kdiff3
  - atom
  - pycharm
  - webstorm
  - nextcloud
  - thunderbird
  - gimp
  - java

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: ""
mas_password: ""
